name: CI

on:
  push:
    branches:
      - '**'
  pull_request:
    branches:
      - '**'

jobs:
  lint:
    name: Lint & Format Check
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18'

      - name: Install dependencies
        run: npm ci

      - name: Run ESLint
        run: npx eslint --ext .js,.jsx,.ts,.tsx,.css .

      - name: Run Prettier check
        run: npx prettier --check .

  build-and-deploy:
    name: Build & Deploy to GitHub Pages
    runs-on: ubuntu-latest
    needs: lint

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18'

      - name: Install dependencies
        run: npm ci
        # Aquí npm ci sí encuentra package-lock.json en la raíz

      - name: Build static site
        run: npm run build
        # Asegúrate de que este comando genere la carpeta `dist` (o corrige si tu carpeta se llama diferente)

      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./dist
          # Sustituye './dist' por la carpeta que genera tu build si es otra (por ejemplo ./build o ./public)